config={}
config['SECRET']='ALanMR33@'
config['SQLALCHEMY_DB_URL']='mysql+pymysql://root:@mysql-service/treelint'
config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
config['MSG_QUEUE'] = 'redis://redis-master'
config['PROJECT_ID'] = 'innate-agency-250312'
config['GS_NAME'] = 'treelint_bucket'
config['MONGO_SERVER'] = 'mongo-service'
config['MONGO_PORT'] = 27017
config['MAIL_SERVER'] = 'smtp.zoho.com'
config['MAIL_PORT'] = 465
config['MAIL_USE_TLS'] = 1
config['MAIL_USERNAME'] = 'info@treelint.com'
config['MAIL_PASSWORD'] = 'ALanMR33@'
config['HDFS'] = 'hadoop-master:50070'
config['HDFS_USER'] = 'root'
config['PREPROCESS_NAME'] = '_preprocess.json'
config['RESULT_NAME'] = '_result.json'
