apiVersion: skaffold/v1beta15
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:1.2.0"
  artifacts:
    - context: .
      image: kai303/tl-web
deploy:
  kubectl:
    manifests:
      - deploy-web/**
profiles:
  - name: cloudbuild
    build:
      googleCloudBuild: {}