apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: ambassador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: backend
          image: kai303/tl-web
          ports:
            - name: http
              containerPort: 8080