apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: ambassador
  labels:
    app: mysql
data:
  my.cnf: |
    # Apply this config only on the master.
    [mysqld]
    bind-address    = 0.0.0.0