apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql
  namespace: ambassador
spec:
  serviceName: "mysql-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql"
              name: mysql-storage
            - name: conf
              mountPath: /etc/mysql/conf.d
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "ALanMR33@"
      volumes:
        - name: conf
          emptyDir: {}
        - name: config-map
          configMap:
            name: mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gcp-class
        resources:
          requests:
            storage: 1Gi