apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: ambassador
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-service
            - name: PMA_PORT
              value: "3306"
            - name: PMA_ABSOLUTE_URI
              value: "https://deretdata.com/phpmyadmin/"
            - name: MYSQL_ROOT_PASSWORD
              value: "ALanMR33@"