apiVersion: apps/v1 
kind: Deployment
metadata:
  name: spark-worker
  namespace: ambassador
spec:
  replicas: 2
  selector:
    matchLabels:
        app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: kai303/tl-spark
          command: ["/opt/spark/bin/spark-class","org.apache.spark.deploy.worker.Worker","spark://spark-master-service:7077"]
          ports:
            - containerPort: 8081
              name: spark