kind: Service
apiVersion: v1
metadata:
  name: spark-master-service
  namespace: ambassador
  labels:
    app: spark-master-service
spec:
  ports:
    - name: sparkwebapi
      port: 6066
      targetPort: 6066
    - name: spark
      port: 7077
      targetPort: 7077
    - name: sparkweb
      port: 8080
      targetPort: 8080
  selector:
    app: spark-master